## Data preprocessing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [34]:
game_data = pd.read_pickle("../testset.pickle")
game_data_keys = game_data.keys()
print(len(game_data_keys))

2470

In [35]:
print(game_data[list(game_data.keys())[0]].keys())
game_data[list(game_data.keys())[0]]

dict_keys(['game_page_url', 'have_att', 'start_time', 'day', 'month', 'is_federal_holiday', 'duration', 'venue', 'at_night', 'on_grass', 'weather_description', 'temperature', 'wind_speed', 'weather', 'precipitation', 'umpires', 'attendance', 'team1_name', 'team1_pre_win', 'team1_pre_loss', 'team1_pre_win_pct', 'team1_players', 'team1_streak', 'team2_name', 'team2_pre_win', 'team2_pre_loss', 'team2_pre_win_pct', 'team2_players', 'team2_streak'])

{'game_page_url': 'https://www.baseball-reference.com/boxes/ANA/ANA202204070.shtml',
 'have_att': True,
 'start_time': datetime.datetime(2022, 4, 7, 18, 38),
 'day': 'Thursday',
 'month': 'April',
 'is_federal_holiday': 0,
 'duration': datetime.timedelta(seconds=11700),
 'venue': 'Angel Stadium of Anaheim',
 'at_night': True,
 'on_grass': True,
 'weather_description': ' 93° F, Wind 6mph out to Rightfield, Sunny, No Precipitation.',
 'temperature': 93,
 'wind_speed': 6,
 'weather': 'Sunny',
 'precipitation': 1,
 'umpires': ' HP - Ed Hickox, 1B - Vic Carapazza, 2B - Jansen Visconti, 3B - Ryan Wills, LF - (none), RF - (none).',
 'attendance': 44723,
 'team1_name': 'HoustonAstros',
 'team1_pre_win': 0,
 'team1_pre_loss': 0,
 'team1_pre_win_pct': 0,
 'team1_players':                 Batting AB  R  H RBI BB SO PA    BA   OBP  ...     WPA    aLI  \
 0        Jose Altuve 2B  4  0  0   0  1  3  5  .000  .200  ...  -0.100   0.78
 1   Michael Brantley DH  5  1  2   0  0  1  5  .400  .400  ...  -0.043   0.88
 2       Alex Bregman 3B  4  1  2   2  0  0  4  .500  .500  ...   0.175   1.07
 3     Yordan Alvarez LF  3  1  1   1  1  0  4  .333  .500  ...   0.044   0.69
 4       Yuli Gurriel 1B  4  0  1   0  0  1  4  .250  .250  ...  -0.045   0.81
 5        Kyle Tucker RF  3  0  0   0  1  1  4  .000  .250  ...  -0.035   0.78
 6        Jeremy Pena SS  4  0  0   0  0  2  4  .000  .000  ...  -0.077   0.76
 7     Chas McCormick CF  4  0  2   0  0  1  4  .500  .500  ...   0.116   0.65
 8    Martin Maldonado C  4  0  0   0  0  1  4  .000  .000  ...  -0.121   0.93
 9      Framber Valdez P                                    ...
 10         Phil Maton P                                    ...
 11       Hector Neris P                                    ...
 12       Ryan Pressly P                                    ...

      WPA+     WPA-    cWPA   acLI   RE24 PO  A Details
 0   0.008  -0.108%  -0.06%   0.79   -0.8  2  3      SB
 1   0.049  -0.092%  -0.03%   0.90   -0.5            2B
 2   0.227  -0.052%   0.11%   1.09    1.4  1  2      HR
 3   0.083  -0.040%   0.03%   0.70    0.8  0  0      HR
 4   0.026  -0.071%  -0.03%   0.82   -0.7  9  0      2B
 5   0.009  -0.044%  -0.02%   0.79   -0.4  2  0      IW
 6   0.000  -0.077%  -0.05%   0.77   -0.8  3  8
 7   0.134  -0.018%   0.07%   0.66    0.9  3  0    2·2B
 8   0.000  -0.121%  -0.07%   0.94   -1.3  7  0
 9                                         0  0
 10                                        0  0
 11                                        0  0
 12                                        0  0

 [13 rows x 24 columns],
 'team1_streak': 0,
 'team2_name': 'LosAngelesAngels',
 'team2_pre_win': 0,
 'team2_pre_loss': 0,
 'team2_pre_win_pct': 0,
 'team2_players':                 Batting AB  R  H RBI BB SO PA    BA   OBP  ...     WPA    aLI  \
 0      Shohei Ohtani DH  4  0  0   0  0  1  4  .000  .000  ...  -0.108   1.02
 1         Mike Trout CF  3  0  1   0  1  1  4  .333  .500  ...   0.162   1.38
 2     Anthony Rendon 3B  4  0  0   0  0  0  4  .000  .000  ...  -0.306   2.14
 3         Matt Duffy 2B  3  0  2   0  0  0  3  .667  .667  ...   0.051   0.80
 4      Tyler Wade PR-2B  1  0  0   0  0  0  1  .000  .000  ...  -0.103   2.54
 5           Jo Adell LF  3  0  0   0  0  3  3  .000  .000  ...  -0.120   1.57
 6        Jared Walsh 1B  3  0  0   0  0  1  3  .000  .000  ...  -0.079   1.07
 7          Max Stassi C  3  0  0   0  0  0  3  .000  .000  ...  -0.056   0.70
 8      Brandon Marsh RF  2  1  0   0  0  1  3  .000  .333  ...  -0.054   0.98
 9     David Fletcher SS  3  0  1   1  0  0  3  .333  .333  ...   0.026   0.88
 10      Shohei Ohtani P                                    ...
 11         Aaron Loup P                                    ...
 12      Austin Warren P                                    ...
 13       Jose Quijada P                                    ...
 14        Ryan Tepera P                                    ...
 15     Archie Bradley P                                    ...

      WPA+     WPA-    cWPA   acLI   RE24  PO  A Details
 0   0.000  -0.108%  -0.06%   0.99   -0.8   0  0
 1   0.192  -0.030%   0.10%   1.34    0.8   3  0
 2   0.000  -0.306%  -0.18%   2.08   -1.8   0  4   2·GDP
 3   0.065  -0.014%   0.03%   0.78    0.4   1  1
 4   0.000  -0.103%  -0.06%   2.48   -0.5   0  0     GDP
 5   0.000  -0.120%  -0.07%   1.53   -0.8   1  0
 6   0.000  -0.079%  -0.05%   1.04   -0.7  10  0
 7   0.000  -0.056%  -0.03%   0.68   -0.5  10  0
 8   0.013  -0.067%  -0.03%   0.96   -0.3   2  0     HBP
 9   0.073  -0.047%   0.01%   0.85    0.8   0  4      3B
 10                                         0  0
 11                                         0  0
 12                                         0  1
 13                                         0  0
 14                                         0  0
 15                                         0  0

 [16 rows x 24 columns],
 'team2_streak': 0}

In [36]:
df_game_data = pd.DataFrame()
for game_key in game_data_keys:
    # game_key = list(game_data.keys())[0]
    game = game_data[game_key]
    df_game = pd.DataFrame([game])
    # print(df_game.head())
    df_game_data = pd.concat([df_game_data, df_game])
df_game_data.head()

,game_page_url,have_att,start_time,day,month,is_federal_holiday,duration,venue,at_night,on_grass,...,team1_pre_loss,team1_pre_win_pct,team1_players,team1_streak,team2_name,team2_pre_win,team2_pre_loss,team2_pre_win_pct,team2_players,team2_streak
0,https://www.baseball-reference.com/boxes/ANA/A...,True,2022-04-07 18:38:00,Thursday,April,0,0 days 03:15:00,Angel Stadium of Anaheim,True,True,...,0,0.0,Batting AB R H RBI BB SO PA ...,0,LosAngelesAngels,0,0,0.0,Batting AB R H RBI BB SO PA ...,0
0,https://www.baseball-reference.com/boxes/ARI/A...,True,2022-04-07 18:40:00,Thursday,April,0,0 days 03:18:00,Chase Field,True,False,...,0,0.0,Batting AB R H RBI BB SO PA...,0,ArizonaDiamondbacks,0,0,0.0,Batting AB R H RBI BB SO ...,0
0,https://www.baseball-reference.com/boxes/ATL/A...,True,2022-04-07 20:08:00,Thursday,April,0,0 days 03:01:00,Truist Park,True,True,...,0,0.0,Batting AB R H RBI BB SO PA ...,0,AtlantaBraves,0,0,0.0,Batting AB R H RBI...,0
0,https://www.baseball-reference.com/boxes/CHN/C...,True,2022-04-07 13:20:00,Thursday,April,0,0 days 03:18:00,Wrigley Field,False,True,...,0,0.0,Batting AB R H RBI BB SO ...,0,ChicagoCubs,0,0,0.0,Batting AB R H RBI B...,0
0,https://www.baseball-reference.com/boxes/KCA/K...,True,2022-04-07 15:10:00,Thursday,April,0,0 days 02:49:00,Kauffman Stadium,False,True,...,0,0.0,Batting AB R H RBI BB SO P...,0,KansasCityRoyals,0,0,0.0,Batting AB R H RBI BB SO PA...,0

In [37]:
df_game_data = df_game_data.reset_index(drop=True)
df_game_data = df_game_data[['attendance', 'start_time', 'day', 'month', 'is_federal_holiday', 
'venue', 'at_night', 'on_grass', 
'temperature', 'wind_speed', 'weather', 'precipitation', 
'team1_name', 'team1_pre_win', 'team1_pre_loss', 
'team1_pre_win_pct', 'team1_players', 'team1_streak', 
'team2_name', 'team2_pre_win', 'team2_pre_loss', 
'team2_pre_win_pct', 'team2_players', 'team2_streak']]
df_game_data.head()

,attendance,start_time,day,month,is_federal_holiday,venue,at_night,on_grass,temperature,wind_speed,...,team1_pre_loss,team1_pre_win_pct,team1_players,team1_streak,team2_name,team2_pre_win,team2_pre_loss,team2_pre_win_pct,team2_players,team2_streak
0,44723,2022-04-07 18:38:00,Thursday,April,0,Angel Stadium of Anaheim,True,True,93,6,...,0,0.0,Batting AB R H RBI BB SO PA ...,0,LosAngelesAngels,0,0,0.0,Batting AB R H RBI BB SO PA ...,0
1,35508,2022-04-07 18:40:00,Thursday,April,0,Chase Field,True,False,93,6,...,0,0.0,Batting AB R H RBI BB SO PA...,0,ArizonaDiamondbacks,0,0,0.0,Batting AB R H RBI BB SO ...,0
2,40545,2022-04-07 20:08:00,Thursday,April,0,Truist Park,True,True,63,15,...,0,0.0,Batting AB R H RBI BB SO PA ...,0,AtlantaBraves,0,0,0.0,Batting AB R H RBI...,0
3,35112,2022-04-07 13:20:00,Thursday,April,0,Wrigley Field,False,True,44,14,...,0,0.0,Batting AB R H RBI BB SO ...,0,ChicagoCubs,0,0,0.0,Batting AB R H RBI B...,0
4,28459,2022-04-07 15:10:00,Thursday,April,0,Kauffman Stadium,False,True,47,16,...,0,0.0,Batting AB R H RBI BB SO P...,0,KansasCityRoyals,0,0,0.0,Batting AB R H RBI BB SO PA...,0

In [11]:
df_game_data.iloc[7320:7330]

,attendance,start_time,day,month,is_federal_holiday,venue,at_night,on_grass,temperature,wind_speed,...,team1_pre_loss,team1_pre_win_pct,team1_players,team1_streak,team2_name,team2_pre_win,team2_pre_loss,team2_pre_win_pct,team2_players,team2_streak
7320,43300,2017-10-29 19:21:00,Sunday,October,0,Minute Maid Park,True,True,69,0,...,57,0.645963,Batting AB R H RBI BB S...,1,HoustonAstros,100,61,0.621118,Batting AB R H RBI BB SO...,-1
7321,54128,2017-10-31 17:21:00,Tuesday,October,0,Dodger Stadium,True,True,67,3,...,60,0.627329,Batting AB R H RBI BB SO ...,1,LosAngelesDodgers,103,58,0.639752,Batting AB R H RBI BB SO...,-1
7322,Start Time: 1:10 p.m. Local,"Rescheduled From: Apr 3, 2017 (Rain)",4,4,0,"Attendance: 36,534",None,None,0,0,...,0,0.000000,Batting AB R H RBI BB S...,0,ChicagoWhiteSox,0,0,0.000000,Batting AB R H RBI BB SO PA ...,0
7323,Start Time: 12:46 p.m. Local,"Rescheduled From: Apr 5, 2017 (Rain)",6,4,0,"Attendance: 44,039",None,None,0,0,...,1,0.500000,Batting AB R H RBI BB SO P...,0,StLouisCardinals,1,1,0.500000,Batting AB R H RBI BB SO ...,0
7324,Start Time: 2:06 p.m. Local,"Rescheduled From: Apr 6, 2017 (Rain)",13,4,0,"Attendance: 32,400",None,None,0,0,...,5,0.375000,Batting AB R H RBI BB S...,0,BostonRedSox,4,4,0.500000,Batting AB R H RBI BB SO PA...,0
7325,40099,2017-04-27 12:47:00,Thursday,April,0,Busch Stadium III,False,True,52,8,...,14,0.300000,Batting AB R H RBI BB SO ...,0,StLouisCardinals,9,11,0.450000,Batting AB R H RBI BB SO P...,2
7326,34779,2017-05-09 12:12:00,Tuesday,May,0,Coors Field,False,True,63,5,...,15,0.516129,Batting AB R H RBI BB...,2,ColoradoRockies,20,12,0.625000,Batting AB R H RBI BB SO...,0
7327,41150,2017-05-14 14:07:00,Sunday,May,0,Yankee Stadium III,False,True,66,7,...,11,0.694444,Batting AB R H RBI BB SO PA ...,0,NewYorkYankees,21,12,0.636364,Batting AB R H RBI BB SO PA...,0
7328,31738,2017-05-14 13:36:00,Sunday,May,0,Nationals Park,False,True,74,13,...,20,0.393939,Batting AB R H RBI BB ...,0,WashingtonNationals,23,12,0.657143,Batting AB R H RBI BB SO PA...,0
7329,20603,2017-05-18 12:11:00,Thursday,May,0,Target Field,False,True,50,12,...,15,0.625000,Batting AB R H RBI BB SO PA ...,1,MinnesotaTwins,19,16,0.542857,Batting AB R H RBI BB S...,0

In [12]:
# df_game_data = df_game_data.drop([7322, 7323, 7324])

In [13]:
df_debug = df_game_data[df_game_data['attendance'] == "Start Time: 12:46 p.m. Local"]
df_debug

Empty DataFrame
Columns: [attendance, start_time, day, month, is_federal_holiday, venue, at_night, on_grass, temperature, wind_speed, weather, precipitation, team1_name, team1_pre_win, team1_pre_loss, team1_pre_win_pct, team1_players, team1_streak, team2_name, team2_pre_win, team2_pre_loss, team2_pre_win_pct, team2_players, team2_streak]
Index: []

[0 rows x 24 columns]

In [38]:
df_game_data = df_game_data.reset_index(drop=True)
df_game_data['attendance'] = df_game_data['attendance'].astype(int)
df_game_data_have_aud = df_game_data[df_game_data['attendance'] > 0].reset_index(drop=True)
print(df_game_data_have_aud.shape)
df_game_data_have_aud.head()

(2445, 24)

,attendance,start_time,day,month,is_federal_holiday,venue,at_night,on_grass,temperature,wind_speed,...,team1_pre_loss,team1_pre_win_pct,team1_players,team1_streak,team2_name,team2_pre_win,team2_pre_loss,team2_pre_win_pct,team2_players,team2_streak
0,44723,2022-04-07 18:38:00,Thursday,April,0,Angel Stadium of Anaheim,True,True,93,6,...,0,0.0,Batting AB R H RBI BB SO PA ...,0,LosAngelesAngels,0,0,0.0,Batting AB R H RBI BB SO PA ...,0
1,35508,2022-04-07 18:40:00,Thursday,April,0,Chase Field,True,False,93,6,...,0,0.0,Batting AB R H RBI BB SO PA...,0,ArizonaDiamondbacks,0,0,0.0,Batting AB R H RBI BB SO ...,0
2,40545,2022-04-07 20:08:00,Thursday,April,0,Truist Park,True,True,63,15,...,0,0.0,Batting AB R H RBI BB SO PA ...,0,AtlantaBraves,0,0,0.0,Batting AB R H RBI...,0
3,35112,2022-04-07 13:20:00,Thursday,April,0,Wrigley Field,False,True,44,14,...,0,0.0,Batting AB R H RBI BB SO ...,0,ChicagoCubs,0,0,0.0,Batting AB R H RBI B...,0
4,28459,2022-04-07 15:10:00,Thursday,April,0,Kauffman Stadium,False,True,47,16,...,0,0.0,Batting AB R H RBI BB SO P...,0,KansasCityRoyals,0,0,0.0,Batting AB R H RBI BB SO PA...,0

In [39]:
from datetime import datetime
df_game_data_have_aud['start_hour'] = df_game_data_have_aud['start_time'].apply(lambda x: datetime.strptime(str(x), '%Y-%m-%d %H:%M:%S').hour)
df_game_data_have_aud.drop('start_time', axis=1, inplace=True)
df_game_data_have_aud.head()

,attendance,day,month,is_federal_holiday,venue,at_night,on_grass,temperature,wind_speed,weather,...,team1_pre_win_pct,team1_players,team1_streak,team2_name,team2_pre_win,team2_pre_loss,team2_pre_win_pct,team2_players,team2_streak,start_hour
0,44723,Thursday,April,0,Angel Stadium of Anaheim,True,True,93,6,Sunny,...,0.0,Batting AB R H RBI BB SO PA ...,0,LosAngelesAngels,0,0,0.0,Batting AB R H RBI BB SO PA ...,0,18
1,35508,Thursday,April,0,Chase Field,True,False,93,6,Sunny,...,0.0,Batting AB R H RBI BB SO PA...,0,ArizonaDiamondbacks,0,0,0.0,Batting AB R H RBI BB SO ...,0,18
2,40545,Thursday,April,0,Truist Park,True,True,63,15,Cloudy,...,0.0,Batting AB R H RBI BB SO PA ...,0,AtlantaBraves,0,0,0.0,Batting AB R H RBI...,0,20
3,35112,Thursday,April,0,Wrigley Field,False,True,44,14,Cloudy,...,0.0,Batting AB R H RBI BB SO ...,0,ChicagoCubs,0,0,0.0,Batting AB R H RBI B...,0,13
4,28459,Thursday,April,0,Kauffman Stadium,False,True,47,16,Cloudy,...,0.0,Batting AB R H RBI BB SO P...,0,KansasCityRoyals,0,0,0.0,Batting AB R H RBI BB SO PA...,0,15

### deal with players

In [16]:
target_player = pd.read_csv("../data/players/players_all_star_salary_5000000.csv")["Name"].to_numpy()
target_player[0:5]

array(['Adam Jones', 'Chris Sale', 'Aroldis Chapman', 'Miguel Cabrera',
       'David Price'], dtype=object)

In [17]:
players_5000000 = pd.read_csv("../data/players/players_salary_5000000.csv")
players_8000000 = pd.read_csv("../data/players/players_salary_8000000.csv")
players_15000000 = pd.read_csv("../data/players/players_salary_15000000.csv")
print(players_5000000.shape, players_8000000.shape, players_15000000.shape)

(585, 1) (391, 1) (172, 1)

In [24]:
df_5000000_8000000 = players_5000000['Name'].isin(players_8000000['Name'])
df_5000000_8000000 = df_5000000_8000000 == False
df_5000000_8000000 = players_5000000[df_5000000_8000000]
df_5000000_8000000 = df_5000000_8000000.reset_index(drop=True)
print(df_5000000_8000000.shape)

(194, 1)

In [25]:
df_8000000_15000000 = players_8000000['Name'].isin(players_15000000['Name'])
df_8000000_15000000 = df_8000000_15000000 == False
df_8000000_15000000 = players_8000000[df_8000000_15000000]
df_8000000_15000000 = df_8000000_15000000.reset_index(drop=True)
print(df_8000000_15000000.shape)

(219, 1)

In [40]:
for player in target_player:
    pl = player.replace(" ", "-")
    record = []
    for i in range(len(df_game_data_have_aud)):
        df_player_1 = df_game_data_have_aud['team1_players'][i]
        df_player_2 = df_game_data_have_aud['team2_players'][i]
        if df_player_1["Batting"].str.contains(player).any() or df_player_2["Batting"].str.contains(player).any():
            record.append(1)
        else:
            record.append(0)
    df_game_data_have_aud[pl] = record

C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1261902906.py:11: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud[pl] = record

In [41]:
df_game_data_have_aud.head()

,attendance,day,month,is_federal_holiday,venue,at_night,on_grass,temperature,wind_speed,weather,...,Corbin-Burnes,Pete-Alonso,Edwin-Díaz,Starling-Marte,Joe-Musgrove,Joc-Pederson,Carlos-Rodon,Corey-Seager,Vladimir-Guerrero-Jr.,Byron-Buxton
0,44723,Thursday,April,0,Angel Stadium of Anaheim,True,True,93,6,Sunny,...,0,0,0,0,0,0,0,0,0,0
1,35508,Thursday,April,0,Chase Field,True,False,93,6,Sunny,...,0,0,0,0,0,0,0,0,0,0
2,40545,Thursday,April,0,Truist Park,True,True,63,15,Cloudy,...,0,0,0,0,0,0,0,0,0,0
3,35112,Thursday,April,0,Wrigley Field,False,True,44,14,Cloudy,...,1,0,0,0,0,0,0,0,0,0
4,28459,Thursday,April,0,Kauffman Stadium,False,True,47,16,Cloudy,...,0,0,0,0,0,0,0,0,0,0

In [42]:
rank1 = []
rank2 = []
rank3 = []
for i in range(len(df_game_data_have_aud)):
    df_player_1 = df_game_data_have_aud['team1_players'][i]
    df_player_2 = df_game_data_have_aud['team2_players'][i]
    rank1_num = 0
    rank2_num = 0
    rank3_num = 0

    # calculate 5000000~8000000
    for j in range(len(df_5000000_8000000)):
        if df_player_1["Batting"].str.contains(df_5000000_8000000['Name'][j]).any() or df_player_2["Batting"].str.contains(df_5000000_8000000['Name'][j]).any():
            rank1_num += 1

    # calculate 8000000~15000000
    for j in range(len(df_8000000_15000000)):
        if df_player_1["Batting"].str.contains(df_8000000_15000000['Name'][j]).any() or df_player_2["Batting"].str.contains(df_8000000_15000000['Name'][j]).any():
            rank2_num += 1

    # calculate 15000000~
    for j in range(len(players_15000000)):
        if df_player_1["Batting"].str.contains(players_15000000['Name'][j]).any() or df_player_2["Batting"].str.contains(players_15000000['Name'][j]).any():
            rank3_num += 1

    rank1.append(rank1_num)
    rank2.append(rank2_num)
    rank3.append(rank3_num)
print(len(rank1), len(rank2), len(rank3))

2445 2445 2445

In [43]:
df_game_data_have_aud['salary-500-800'] = rank1
df_game_data_have_aud['salary-800-1500'] = rank2
df_game_data_have_aud['salary-1500'] = rank3

C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1281861877.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud['salary-500-800'] = rank1
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1281861877.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud['salary-800-1500'] = rank2
C:\Users\gary6\AppData\Local\Temp\ipykernel_28596\1281861877.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_game_data_have_aud['salary-1500'] = rank3

In [44]:
df_game_data_have_aud.drop(['team1_players', 'team2_players'], axis=1, inplace=True)

In [45]:
df_game_data_have_aud.head()

,attendance,day,month,is_federal_holiday,venue,at_night,on_grass,temperature,wind_speed,weather,...,Starling-Marte,Joe-Musgrove,Joc-Pederson,Carlos-Rodon,Corey-Seager,Vladimir-Guerrero-Jr.,Byron-Buxton,salary-500-800,salary-800-1500,salary-1500
0,44723,Thursday,April,0,Angel Stadium of Anaheim,True,True,93,6,Sunny,...,0,0,0,0,0,0,0,5,3,4
1,35508,Thursday,April,0,Chase Field,True,False,93,6,Sunny,...,0,0,0,0,0,0,0,4,1,5
2,40545,Thursday,April,0,Truist Park,True,True,63,15,Cloudy,...,0,0,0,0,0,0,0,4,5,3
3,35112,Thursday,April,0,Wrigley Field,False,True,44,14,Cloudy,...,0,0,0,0,0,0,0,5,4,4
4,28459,Thursday,April,0,Kauffman Stadium,False,True,47,16,Cloudy,...,0,0,0,0,0,0,0,2,2,4

In [46]:
df_game_data_have_aud.to_csv("processed_test.csv", index=False)